baseURL: https://cable-robots.gitlab.io/latex/
languageCode: en-us
title: Cable Robots LaTeX
theme: book

# Book configuration
disablePathToLower: false
enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm
params:
  BookComments: false
  BookRepo: https://cable-robots.gitlab.io/latex/
  BookEditPath: -/edit/docs/content/
  BookToC: true
